### ISSUE TITLE
**Please Choose A Differrent Name. [FINAL WARNING]**

### ISSUE THREAD

**Issue by SharkFinPro** [SharkFinProductions/Salanbaty.js#2]
@XtremePlayzCODE You are amazing. I understand you already changed the name. You are so awesome

**Comment by Fantasy-Agario** [comment]
Who is this aimed at ?

**Comment by SharkFinPro** [comment]
@XtremePlayzCODE

**Comment by Fantasy-Agario** [comment]
Oh ok :)

**Comment by XtremePlayzCODE** [comment]
Yeah sure I did and also edited your issue ;)

**Comment by XtremePlayzCODE** [comment]
I would of went for Ghajklamytinz.js
